#!/usr/bin/env bash

function main {
  local shome="${_wtf_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source "wtf_common"

	tf remote config -backend=s3 -backend-config="bucket=$(CONTEXT_ORG)-remote-state" -backend-config="key=$(CONTEXT_ORG)-remote-state/env-$(CONTEXT_ORG)-$(shell basename "$(shell pwd)" | cut -d- -f3-).tfstate" -backend-config="region=$(shell aws configure get region)"
}

source sub "$BASH_SOURCE" "$@"

