#!/usr/bin/env bash

function main {
  local shome="${_wtf_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source "wtf_common"

  tf remote config "$@"
}

source sub "$BASH_SOURCE" "$@"

