#!/usr/bin/env bash

function main {
  local shome="${_wtf_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source "wtf_common"

  local nm_env="${CONTEXT_ACCOUNT}"

  tf "$nm_env" plan -detailed-exitcode "$@"
}

source sub "$BASH_SOURCE" "$@"
