#!/usr/bin/env bash

function main {
  local shome="${_wtf_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source "wtf_common"

  cd "_${nm_env}"
  jq -r '.modules[] | (reduce .path[] as $p (""; . + "/" + $p)) as $path | .outputs | to_entries[] | "\($path) \(.key) \(.value)"' < "terraform.tfstate"
}

source sub "$BASH_SOURCE" "$@"
