#!/usr/bin/env bash

local nm_env="${CONTEXT_ORG}-${CONTEXT_ENV}"

function tf {
  local nm_cmd="$1"; shift

  local opt_tf_vars="-var-file=terraform.tfvars"

  mkdir -p "_${CONTEXT_ENV}"
	exec terraform "$nm_cmd" ${opt_tf_vars} \
    -var "vpc_name=${CONTEXT_ORG}-${CONTEXT_ENV}" \
         -var-file="_${CONTEXT_ENV}/terraform.tfvars" \
            -state="_${CONTEXT_ENV}/terraform.tfstate" \
           -backup="_${CONTEXT_ENV}/terraform.tfstate.backup" \
    "$@"
}

