#!/usr/bin/env bash

local nm_env="${CONTEXT_ORG}-${CONTEXT_ENV}"

function tf {
  if [[ -z "${CONTEXT_ORG:-}" ]]; then
    exec "$(basename "$(pwd)" | cut -d- -f2)" wtf "$@"
  fi

  if [[ -z "${CONTEXT_ENV:-}" ]]; then
    exec "$(basename "$(pwd)" | cut -d- -f3)" wtf "$@"
  fi

  tf_inner "$@"
}

function tf_inner {
  local nm_cmd="$1"; shift

  case "$nm_cmd" in
    get)
      terraform get "$@"
      ;;

    remote)
      case "${1:-}" in
        config)
          shift
          terraform remote config -backend=s3 -backend-config="bucket=${CONTEXT_ORG}-remote-state" -backend-config="key=${CONTEXT_ORG}-remote-state/env-${CONTEXT_ORG}-$(basename "$(pwd)" | cut -d- -f3-).tfstate" -backend-config="region=$(aws configure get region)"
          ;;
        *)
          terraform remote "$@"
          ;;
      esac
      ;;

    *)
      terraform "$nm_cmd" \
        -var "vpc_name=${CONTEXT_ORG}-${CONTEXT_ENV}" \
        -var "context_org=${CONTEXT_ORG}" \
        -var "context_env=${CONTEXT_ENV}" \
        -var "bucket_remote_state=${CONTEXT_ORG}-remote-state" \
        "$@"
      ;;
  esac
}
