#!/usr/bin/env bash

function bootstrap {
  local shome="${_wtf_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  block compile virtualenv

  "$shome/script/update"
}

bootstrap
